# Generated by Django 3.2.9 on 2021-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211130_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
