# Generated by Django 3.2.9 on 2021-11-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pricing_description', models.TextField(max_length=254)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Testamonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testamonial_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('testamonal_review', models.TextField()),
                ('persons_name', models.CharField(max_length=50)),
                ('persons_work', models.CharField(max_length=50)),
            ],
        ),
    ]
