# Generated by Django 3.2.9 on 2021-11-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_testamonials_testamonal_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='testamonials',
            options={'verbose_name_plural': 'Testamonials'},
        ),
        migrations.RenameField(
            model_name='testamonials',
            old_name='testamonal_rating',
            new_name='testamonial_rating',
        ),
        migrations.RenameField(
            model_name='testamonials',
            old_name='testamonal_review',
            new_name='testamonial_review',
        ),
    ]
