# Generated by Django 3.2.9 on 2021-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequestmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequestmodel',
            options={'verbose_name': 'Service Requests'},
        ),
        migrations.RemoveField(
            model_name='servicerequestmodel',
            name='request',
        ),
        migrations.AddField(
            model_name='servicerequestmodel',
            name='Ideas',
            field=models.TextField(default=''),
        ),
    ]
