# Generated by Django 3.2.9 on 2021-12-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20211130_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequestmodel',
            options={'verbose_name': 'Service Request', 'verbose_name_plural': 'Service Requests'},
        ),
        migrations.RenameField(
            model_name='servicerequestmodel',
            old_name='Ideas',
            new_name='ideas',
        ),
    ]
