# Generated by Django 3.2.9 on 2021-12-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
