# Generated by Django 3.2.9 on 2021-11-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
