# Generated by Django 3.2.9 on 2021-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstyles',
            name='style_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
