# Generated by Django 3.2.9 on 2021-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0002_shopstyles_style_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstyles',
            name='url_field',
            field=models.URLField(default=''),
        ),
    ]
