# Generated by Django 3.2.9 on 2021-12-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styles', '0003_shopstyles_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstyles',
            name='url_field',
            field=models.URLField(default='', null=True),
        ),
    ]
